swagger: 2.0
info:
  description: Elephant APIs
  version: 1.0.0
  title: Elephant
tags:
- name: admin
  description: APIs for Admin Panel
schemes:
- http
- https
paths:
  /api/category/get:
    get:
      tags:
        - admin
      summary: Get category data
      description: Get category data
      operationId: getCategory
      produces:
        - application/json
      parameters:
        - name: id
          in: query
          description: Category ID
          required: true
          type: string
      responses:
        200:
          description: OK
          schema:
            $ref: "#/definitions/Category"
        400:
          description: INVALID_ARGUMENT
          schema:
            $ref: "#/definitions/InvalidArgumentErrorResponse"
        500:
          description: INTERNAL
          schema:
            $ref: "#/definitions/InternalErrorResponse"
definitions:
  Category:
    type: object
    properties:
      id:
        type: string
        example: 1707290001
      name:
        $ref: "#/definitions/Names"
      is_root:
        type: boolean
        example: true
      children:
        type: array
        items:
          type: string
        example:
          - 1707280002
          - 1707280003
      created_at:
        type: integer
        format: int64
      updated_at:
        type: integer
        format: int64
  Names:
    type: object
    example:
      english: name in english
      hindi: name in hindi
  InvalidArgumentErrorResponse:
    type: object
    properties:
      status:
        type: string
        example: INVALID_ARGUMENT
      error:
        type: string
        example: need a valid id.
  InternalErrorResponse:
    type: object
    properties:
      status:
        type: string
        example: INTERNAL
      error:
        type: string
        example: something went wrong.
