version: '2'
services:
  app:
    build: .
    command: make run
    volumes:
      - ./:/elephant
    environment:
      NODE_ENV: dev
    ports:
      - "17883:17883"
    links:
      - mongo
    logging:
      driver: "json-file"
  mongo:
     image: mongo:3.4.5
     volumes:
       - ~/workspace/data/mongo:/data/db:rw
     ports:
       - "27017:27017"
     logging:
       driver: "json-file"
